security:
  oauth2:
    client:
      client-id: hwaju3
      client-secret: teamfreshpwd
    resource:
      jwt:
        key-value: sdsfadsfewqrgewqrgavsyhyjmyfur5tym5346234gbbh3e4r5fq324453254


spring:
  h2:    console:      enabled: true
  data:
    jpa:
      repositories:
        enabled: 'true'
  datasource:    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:      auto-commit: false
  jpa:
    hibernate:
      show-sql: 'true'
      format_sql: 'true'
      use_sql_comments: 'true'
      ddl-auto: update
       
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.connection.provider_disables_autocommit: true
  devtools:
    livereload:
      enabled: 'true'
  mvc:
    throw-exception-if-no-handler-found: 'true'
  resources:
    add-mappings: 'false'
 
server:
  port: '8080'
logging:
  level:
    org:
      hibernate:
        type: debug
    root: debug